### POSTS
### Get all posts

GET http://localhost:3000/api/posts?page=3
Content-Type: application/json

### Create new post
POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "title": "Emil228s",
    "description": "Pedor",
    "is_published": true,
    "category_id": 6
}

### Update post
PATCH http://localhost:3000/api/posts/1
Content-Type: application/json

{
    "title": "Emil",
    "description": "Pedor",
    "is_published": true,
    "category_id": 1
}

### Delete post
DELETE http://localhost:3000/api/posts/1
Content-Type: application/json

### CATEGORIES
### Get all categories

GET http://localhost:3000/api/categories/5?page=1
Content-Type: application/json

### Create new category
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "title": "Category 2"
}

### Update category
PATCH http://localhost:3000/api/categories/5
Content-Type: application/json

{
    "title": "Emil"
}

### Delete category
DELETE http://localhost:3000/api/categories/1
Content-Type: application/json

### AUTH
### Sign up
POST http://localhost:3000/api/users/sign-up
Content-Type: application/json

{
    "name": "email",
    "password": "emilain2228",
    "email": "email2@gmail.com"
}

### Sign in
POST http://localhost:3000/api/users/sign-in
Content-Type: application/json

{
    "password": "emilain2228",
    "email": "email2@gmail.com"
}

### Protected user list
PATCH http://localhost:3000/api/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVtYWlsIiwic3ViIjoyLCJpYXQiOjE2NzAyNTE2NjgsImV4cCI6MTY3MDI1MTcyOH0.7hsB5MUJ2z_aiYqk6GvJU5NcYpKBilP_pxBk3s3NymM

{
    "is_admin": true
}