import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, JoinColumn } from "typeorm";
import { CategoryEntity } from "src/categories/category.entity";
import { UserEntity } from "src/users/user.entity";

@Entity()
export class PostEntity {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        type: "varchar",
        nullable: false
    })
    title: string;

    @Column({
        type: "text",
        nullable: true
    })
    description: string;

    @Column({
        default: false
    })
    is_published: boolean;

    @Column({
        type: "timestamp",
        default: () => "CURRENT_TIMESTAMP()"
    })
    created_at: Date;

    @Column({
        type: "timestamp",
        default: () => "CURRENT_TIMESTAMP()",
        onUpdate: "CURRENT_TIMESTAMP()"
    })
    updated_at: Date;

    // Autogenerated, but need to be declared in case of TS is pidaras
    @Column({
        nullable: true
    })
    categoryId: number;

    @ManyToOne(() => CategoryEntity, (category) => category.posts, {
        cascade: true
    })
    category: CategoryEntity;

    @Column({
        nullable: true
    })
    userId: number;
       
    @ManyToOne(() => UserEntity, (user) => user.posts, {
        cascade: true,
    })
    user: UserEntity;
}
